### ISSUE TITLE
Suggestion: random rotation for cultivated plants and props, brush presets

### ISSUE THREAD

**Issue by Haneybd87** [yenyang/Tree_Controller_BepInEx#1]
It would be really nice to have random rotation for all of the cultivated plants just like the wild plants and trees. It would also come in really handy for props but especially for boulders and rocks. 

Another nice thing would be if we could make a custom mixed brush to make our own mix of plants and trees.

Anyways I don't know if any of this is possible but just thought I'd throw it out there.

**Comment by yenyang** [comment]
Random rotation for plants, rocks, and other props can probably be included in whatever mod ends up doing prop control. I don't know if I will do it or someone else. For now this mod is just entities with Tree component which does include wild bushes but doesn't include cultivated plants. 

Custom mixed brushes is a planned feature. I have started working on it. I hope it is done soon and included in next update. I don't know how to deal with cultivated plants. Right now they're excluded from the feature, but it's annoying since they're in the same menu.

**Comment by yenyang** [comment]
For cultivated plants this got added into the update for V1.1
